### ISSUE TITLE
Gem installtion is failing

### ISSUE THREAD

**Issue by zeeporter** [harikesh-kolekar/super_receptionist#1]
Seems like this gem is not yet available to be installed.
Getting this error while bundling
Could not find gem 'super_receptionist' in any of the gem sources listed in your Gemfile.

**Comment by harikesh-kolekar** [comment]
@zeeporter All feature of the gem was not completed, so it's not published, now its published in https://rubygems.org.
Now you can install it.

**Comment by harikesh-kolekar** [comment]
now its published in https://rubygems.org.
